-- =============================================================================
-- DEMO-INHALTE  ·  nur zum Testen der Oberflaeche
--
-- Diese Karten sind KEINE Produktionsinhalte. Sie sind von Hand geschrieben,
-- damit der Feed etwas anzeigen kann, bevor die Pipeline steht - genau das,
-- wovon docs/CONTENT-SOURCING.md abraet. Bewusst deshalb:
--   * ausschliesslich zeitlose, robuste Fakten (keine Zahlen, die veralten)
--   * media enthaelt {"demo": true} - so sind sie jederzeit auffindbar
--
-- Loeschen, sobald die Pipeline echte Inhalte liefert:
--   delete from public.content_items where media->>'demo' = 'true';
-- =============================================================================

insert into public.content_items (
  content_type, presentation_mode, status, title, deck, body_blocks,
  source_ids, source_urls, primary_source_id, published_at,
  language, region_code, primary_category_id, category_ids,
  difficulty, word_count, quiz_items, media, content_hash
) values

-- === DEUTSCH · Wissen =======================================================

('knowledge','text','approved',
 'Die 72er-Regel',
 'Wie lange dein Geld braucht, um sich zu verdoppeln - im Kopf gerechnet.',
 '[{"type":"para","text":"Teile 72 durch den Zinssatz in Prozent. Das Ergebnis sind ungefähr die Jahre bis zur Verdopplung."},
   {"type":"stat","value":"72 ÷ 7 ≈ 10","label":"Jahre bis zur Verdopplung bei 7 Prozent"},
   {"type":"para","text":"Die Regel ist eine Näherung für den Zinseszins und wird ungenauer, je weiter der Zinssatz von 8 Prozent entfernt liegt. Für Kopfrechnen im Alltag reicht sie fast immer."}]'::jsonb,
 array['internal-de'], array['https://de.wikipedia.org/wiki/72er-Regel'], 'internal-de', now() - interval '2 days',
 'de', null, 'finance.compound', array['finance.compound','finance.basics'],
 2, 62,
 '[{"question":"Wie lange dauert die Verdopplung bei 6 Prozent ungefähr?","options":["6 Jahre","12 Jahre","24 Jahre"],"correct_index":1,"explanation":"72 ÷ 6 = 12."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-de-rule72'),

('knowledge','text','approved',
 'Warum Pausen dich schlauer machen',
 'Verteiltes Lernen schlägt Blockpauken - und zwar deutlich.',
 '[{"type":"para","text":"Denselben Stoff über mehrere Tage verteilt zu lernen führt zu deutlich besserem Langzeitbehalten als dieselbe Zeit am Stück. Der Effekt heißt Spacing-Effekt und gehört zu den am besten belegten Befunden der Lernforschung."},
   {"type":"bullet","items":["Vier mal 15 Minuten an vier Tagen schlagen eine Stunde am Stück.","Der Effekt wird größer, je länger man das Wissen behalten will.","Blockpauken fühlt sich flüssiger an - genau das täuscht."]}]'::jsonb,
 array['internal-de'], array['https://de.wikipedia.org/wiki/Verteiltes_Lernen'], 'internal-de', now() - interval '1 day',
 'de', null, 'mind.learning', array['mind.learning','mind.focus'],
 2, 71,
 '[{"question":"Warum überschätzen viele das Blockpauken?","options":["Weil es länger dauert","Weil es sich flüssiger anfühlt","Weil es mehr Stoff abdeckt"],"correct_index":1,"explanation":"Flüssigkeit im Moment wird mit Behalten verwechselt."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-de-spacing'),

('knowledge','text','approved',
 'Acht Minuten Verspätung',
 'Das Sonnenlicht, das du gerade siehst, ist älter als du denkst.',
 '[{"type":"para","text":"Licht legt rund 300.000 Kilometer pro Sekunde zurück. Von der Sonne bis zur Erde braucht es etwa acht Minuten und zwanzig Sekunden."},
   {"type":"para","text":"Würde die Sonne in diesem Moment erlöschen, bliebe es hier noch gut acht Minuten hell. Beim Blick in den Nachthimmel wird der Effekt extrem: manches Sternenlicht ist Tausende Jahre alt."}]'::jsonb,
 array['internal-de'], array['https://www.esa.int'], 'internal-de', now() - interval '3 days',
 'de', null, 'science.space', array['science.space','science.physics'],
 1, 58,
 '[{"question":"Wie lange braucht Sonnenlicht bis zur Erde?","options":["8 Sekunden","8 Minuten","8 Stunden"],"correct_index":1,"explanation":"Rund 8 Minuten und 20 Sekunden."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-de-lightdelay'),

('knowledge','text','approved',
 'Die erste Nachthälfte zählt',
 'Tiefschlaf ist nicht gleichmäßig über die Nacht verteilt.',
 '[{"type":"para","text":"Der Schlaf läuft in Zyklen von etwa 90 Minuten. Der Tiefschlafanteil ist in den ersten Zyklen am größten und nimmt gegen Morgen ab. Der REM-Anteil verhält sich umgekehrt."},
   {"type":"para","text":"Wer spät ins Bett geht und trotzdem zur gleichen Zeit aufsteht, verliert deshalb überproportional viel REM-Schlaf - nicht einfach gleichmäßig von allem etwas."}]'::jsonb,
 array['internal-de'], array['https://de.wikipedia.org/wiki/Schlaf'], 'internal-de', now() - interval '4 days',
 'de', null, 'body.sleep', array['body.sleep','mind.focus'],
 3, 64,
 '[{"question":"Was verliert man vor allem, wenn man zu spät ins Bett geht?","options":["Tiefschlaf","REM-Schlaf","Beides gleich viel"],"correct_index":1,"explanation":"REM-Schlaf liegt vor allem in der zweiten Nachthälfte."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-de-sleep'),

('knowledge','text','approved',
 'Was ist ein Token?',
 'Sprachmodelle lesen keine Wörter - sie lesen Bruchstücke.',
 '[{"type":"para","text":"Ein Sprachmodell zerlegt Text vor der Verarbeitung in Tokens. Ein Token ist meist ein halbes bis ganzes Wort, bei seltenen Begriffen auch nur ein paar Buchstaben."},
   {"type":"bullet","items":["Häufige Wörter werden zu einem einzigen Token.","Seltene oder zusammengesetzte Wörter zerfallen in mehrere.","Deutsche Texte brauchen typischerweise mehr Tokens als englische."]},
   {"type":"para","text":"Deshalb kostet dieselbe Aussage auf Deutsch oft mehr als auf Englisch."}]'::jsonb,
 array['internal-de'], array['https://de.wikipedia.org/wiki/Tokenisierung'], 'internal-de', now() - interval '1 day',
 'de', null, 'tech.ai', array['tech.ai','tech.code'],
 3, 74,
 '[{"question":"Warum brauchen deutsche Texte oft mehr Tokens?","options":["Weil Deutsch mehr Buchstaben nutzt","Wegen langer und zusammengesetzter Wörter","Weil Modelle Deutsch nicht kennen"],"correct_index":1,"explanation":"Komposita zerfallen in mehrere Tokens."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-de-token'),

('knowledge','text','approved',
 'Warum der Himmel blau ist',
 'Nicht wegen des Meeres - wegen der Wellenlänge.',
 '[{"type":"para","text":"Luftmoleküle streuen kurzwelliges Licht viel stärker als langwelliges. Blau wird deshalb in alle Richtungen verteilt und erreicht das Auge aus dem ganzen Himmel."},
   {"type":"para","text":"Bei Sonnenuntergang läuft das Licht durch viel mehr Atmosphäre. Der blaue Anteil wird unterwegs weggestreut, übrig bleibt Rot."}]'::jsonb,
 array['internal-de'], array['https://de.wikipedia.org/wiki/Rayleigh-Streuung'], 'internal-de', now() - interval '5 days',
 'de', null, 'science.physics', array['science.physics'],
 2, 56,
 '[{"question":"Warum ist der Sonnenuntergang rot?","options":["Die Sonne kühlt ab","Blaues Licht wird auf dem längeren Weg weggestreut","Staub färbt das Licht"],"correct_index":1,"explanation":"Längerer Weg durch die Atmosphäre streut Blau heraus."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-de-rayleigh'),

('knowledge','text','approved',
 'Der Bestätigungsfehler',
 'Wir suchen nicht nach der Wahrheit, sondern nach Zustimmung.',
 '[{"type":"para","text":"Menschen suchen und gewichten bevorzugt Informationen, die zur eigenen Erwartung passen. Widersprechende Belege werden strenger geprüft als bestätigende."},
   {"type":"quote","text":"Der Fehler liegt nicht darin, eine Meinung zu haben, sondern darin, nur nach Belegen dafür zu suchen.","attribution":"Kernidee der Verzerrungsforschung"},
   {"type":"para","text":"Ein wirksames Gegenmittel: gezielt nach dem stärksten Argument der Gegenseite suchen, nicht nach dem schwächsten."}]'::jsonb,
 array['internal-de'], array['https://de.wikipedia.org/wiki/Best%C3%A4tigungsfehler'], 'internal-de', now() - interval '2 days',
 'de', null, 'mind.bias', array['mind.bias','mind.learning'],
 2, 68,
 '[{"question":"Was ist ein wirksames Gegenmittel?","options":["Mehr Quellen der eigenen Seite lesen","Das stärkste Gegenargument suchen","Sich keine Meinung bilden"],"correct_index":1,"explanation":"Gezielt die beste Gegenposition prüfen."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-de-bias'),

('knowledge','text','approved',
 'Inflation frisst leise',
 'Zwei Prozent klingen harmlos. Über zwanzig Jahre sind sie es nicht.',
 '[{"type":"para","text":"Bei zwei Prozent jährlicher Inflation verliert Geld in zwanzig Jahren rund ein Drittel seiner Kaufkraft."},
   {"type":"stat","value":"≈ 33 %","label":"Kaufkraftverlust nach 20 Jahren bei 2 % Inflation"},
   {"type":"para","text":"Der Grund ist derselbe wie beim Zinseszins - nur in die andere Richtung. Kleine jährliche Effekte summieren sich nicht, sie multiplizieren sich."}]'::jsonb,
 array['internal-de'], array['https://www.statistik.at'], 'internal-de', now() - interval '6 days',
 'de', null, 'finance.basics', array['finance.basics','finance.macro'],
 2, 59,
 '[{"question":"Warum wirkt Inflation über lange Zeit so stark?","options":["Weil sie jedes Jahr steigt","Weil sie sich multipliziert statt zu addieren","Weil Löhne sinken"],"correct_index":1,"explanation":"Zinseszins-Logik, nur negativ."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-de-inflation'),

-- === DEUTSCH · News-Format ==================================================

('news','text','approved',
 'Ein Ring von 27 Kilometern',
 'Der größte Teilchenbeschleuniger der Welt liegt unter der Grenze zweier Länder.',
 '[{"type":"para","text":"Der Large Hadron Collider am CERN hat einen Umfang von rund 27 Kilometern und verläuft in etwa 100 Metern Tiefe unter der Grenze zwischen Frankreich und der Schweiz."},
   {"type":"para","text":"In ihm werden Protonen fast auf Lichtgeschwindigkeit gebracht und zur Kollision geführt. Die Magnete, die sie auf Kurs halten, werden dafür auf unter minus 271 Grad Celsius gekühlt."}]'::jsonb,
 array['cern'], array['https://home.cern/science/accelerators/large-hadron-collider'], 'cern', now() - interval '12 hours',
 'de', null, 'world.science', array['world.science','science.physics'],
 2, 66,
 '[{"question":"Wie groß ist der Umfang des LHC ungefähr?","options":["2,7 Kilometer","27 Kilometer","270 Kilometer"],"correct_index":1,"explanation":"Rund 27 Kilometer."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-de-lhc'),

('news','text','approved',
 'Anderthalb Millionen Kilometer entfernt',
 'Warum das James-Webb-Teleskop nicht um die Erde kreist.',
 '[{"type":"para","text":"Das James-Webb-Weltraumteleskop steht nicht in einer Erdumlaufbahn, sondern am Lagrange-Punkt L2 - rund 1,5 Millionen Kilometer von der Erde entfernt, auf der sonnenabgewandten Seite."},
   {"type":"para","text":"Dort bleibt es dauerhaft im Schatten von Erde und Sonne und kann seine Instrumente passiv auf unter minus 220 Grad kühlen. Für Infrarot-Beobachtung ist genau das entscheidend."}]'::jsonb,
 array['nasa','esa'],
 array['https://science.nasa.gov/mission/webb/','https://www.esa.int/Science_Exploration/Space_Science/Webb'],
 'nasa', now() - interval '20 hours',
 'de', null, 'world.science', array['world.science','science.space'],
 3, 69,
 '[{"question":"Warum steht Webb am Punkt L2?","options":["Dort ist es näher an anderen Galaxien","Es bleibt im Schatten und kann passiv kühlen","Dort ist weniger Weltraumschrott"],"correct_index":1,"explanation":"Konstanter Schatten ermöglicht passive Kühlung."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-de-jwst'),

('news','text','approved',
 'Neun Länder, ein Staat',
 'Österreichs föderaler Aufbau in einer Minute.',
 '[{"type":"para","text":"Österreich besteht aus neun Bundesländern. Wien ist gleichzeitig Bundesland und Gemeinde - eine Konstruktion, die es sonst in Österreich nicht gibt."},
   {"type":"bullet","items":["Jedes Bundesland hat einen eigenen Landtag mit eigener Gesetzgebung.","Bildung, Naturschutz und Bauordnung sind stark landesabhängig.","Deshalb unterscheiden sich Schulregeln zwischen Wien und Kärnten spürbar."]}]'::jsonb,
 array['statistik-at'], array['https://www.statistik.at'], 'statistik-at', now() - interval '1 day',
 'de', 'AT', 'local.at', array['local.at','world.politics'],
 1, 63,
 '[{"question":"Was ist an Wien besonders?","options":["Es ist das größte Bundesland","Es ist Bundesland und Gemeinde zugleich","Es hat keinen Landtag"],"correct_index":1,"explanation":"Wien ist gleichzeitig Gemeinde und Bundesland."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-de-at9'),

('news','text','approved',
 'Wie die EU Gesetze macht',
 'Kommission schlägt vor, Parlament und Rat entscheiden.',
 '[{"type":"para","text":"Im ordentlichen Gesetzgebungsverfahren der EU schlägt die Kommission ein Gesetz vor. Beschließen müssen es anschließend zwei Organe gemeinsam: das direkt gewählte Europäische Parlament und der Rat, in dem die Mitgliedstaaten sitzen."},
   {"type":"para","text":"Ohne Zustimmung beider kommt kein Gesetz zustande. Die Kommission kann also vorschlagen, aber nicht allein entscheiden."}]'::jsonb,
 array['eu-kom-de'], array['https://ec.europa.eu/commission/presscorner'], 'eu-kom-de', now() - interval '2 days',
 'de', null, 'world.politics', array['world.politics'],
 3, 65,
 '[{"question":"Wer muss einem EU-Gesetz zustimmen?","options":["Nur die Kommission","Parlament und Rat gemeinsam","Nur die Mitgliedstaaten"],"correct_index":1,"explanation":"Beide Organe müssen zustimmen."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-de-eu'),

-- === ENGLISCH ===============================================================

('knowledge','text','approved',
 'Halving the haystack',
 'Why binary search feels like magic on large data.',
 '[{"type":"para","text":"Binary search discards half of the remaining candidates with every step. Doubling the size of the data adds exactly one step, not twice the work."},
   {"type":"stat","value":"1,000,000 → 20","label":"steps needed to find any item"},
   {"type":"para","text":"The catch: the data has to be sorted first. Sorting is the expensive part, which is why databases keep indexes around instead of sorting on every query."}]'::jsonb,
 array['internal-en'], array['https://en.wikipedia.org/wiki/Binary_search'], 'internal-en', now() - interval '1 day',
 'en', null, 'tech.code', array['tech.code'],
 3, 70,
 '[{"question":"What does doubling the data add?","options":["Twice the steps","One extra step","No change"],"correct_index":1,"explanation":"Logarithmic growth: one more halving."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-en-binsearch'),

('knowledge','text','approved',
 'Your cells run on a gradient',
 'Mitochondria do not burn sugar directly. They build a battery.',
 '[{"type":"para","text":"Mitochondria pump protons across an inner membrane, creating a difference in charge and concentration. Energy is stored in that imbalance, not in the sugar itself."},
   {"type":"para","text":"Protons then flow back through an enzyme that spins like a turbine, and that rotation assembles ATP - the molecule almost every process in the cell pays with."}]'::jsonb,
 array['internal-en'], array['https://en.wikipedia.org/wiki/Oxidative_phosphorylation'], 'internal-en', now() - interval '3 days',
 'en', null, 'science.bio', array['science.bio'],
 4, 62,
 '[{"question":"Where is the energy stored just before ATP is made?","options":["In glucose","In a proton gradient","In the cell nucleus"],"correct_index":1,"explanation":"The gradient across the inner membrane is the store."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-en-mito'),

('knowledge','text','approved',
 'The only free lunch',
 'Diversification lowers risk without lowering expected return.',
 '[{"type":"para","text":"Holding many assets that do not move in lockstep reduces the swings of a portfolio. Because the expected return is the weighted average, it does not fall along with the risk."},
   {"type":"bullet","items":["Only the risk specific to one company disappears.","Market-wide risk stays no matter how many stocks you hold.","Adding more of the same sector diversifies far less than it looks."]}]'::jsonb,
 array['internal-en'], array['https://en.wikipedia.org/wiki/Diversification_(finance)'], 'internal-en', now() - interval '4 days',
 'en', null, 'finance.markets', array['finance.markets','finance.basics'],
 3, 68,
 '[{"question":"Which risk does diversification NOT remove?","options":["Company-specific risk","Market-wide risk","Sector risk"],"correct_index":1,"explanation":"Systematic risk cannot be diversified away."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-en-diversify'),

('knowledge','text','approved',
 'Progressive overload',
 'Muscles adapt to demands they have already met, not to effort.',
 '[{"type":"para","text":"Training only keeps producing adaptation when the demand keeps rising - more weight, more repetitions, more sets, or less rest. Repeating the identical session indefinitely stops working once the body has adapted."},
   {"type":"para","text":"The increases can be small. What matters is that they are systematic rather than random."}]'::jsonb,
 array['internal-en'], array['https://en.wikipedia.org/wiki/Progressive_overload'], 'internal-en', now() - interval '5 days',
 'en', null, 'body.training', array['body.training'],
 2, 57,
 '[{"question":"Why does the same workout stop working?","options":["Muscles get bored","The body has already adapted to that demand","Technique degrades"],"correct_index":1,"explanation":"Adaptation removes the stimulus."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-en-overload'),

('news','text','approved',
 'A ring 27 kilometres around',
 'The largest particle accelerator sits under two countries.',
 '[{"type":"para","text":"The Large Hadron Collider at CERN is about 27 kilometres in circumference and runs roughly 100 metres underground, crossing the border between France and Switzerland."},
   {"type":"para","text":"Protons are accelerated to nearly the speed of light before colliding. The magnets that steer them are cooled below minus 271 degrees Celsius."}]'::jsonb,
 array['cern'], array['https://home.cern/science/accelerators/large-hadron-collider'], 'cern', now() - interval '14 hours',
 'en', null, 'world.science', array['world.science','science.physics'],
 2, 60,
 '[{"question":"Roughly how large is the LHC ring?","options":["2.7 km","27 km","270 km"],"correct_index":1,"explanation":"About 27 kilometres."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-en-lhc'),

('news','text','approved',
 'Parked in a permanent shadow',
 'Why the Webb telescope does not orbit Earth.',
 '[{"type":"para","text":"The James Webb Space Telescope sits at Lagrange point L2, about 1.5 million kilometres from Earth on the side facing away from the Sun."},
   {"type":"para","text":"Staying in that shadow lets it cool passively to below minus 220 degrees Celsius, which infrared observation requires. An orbit around Earth would repeatedly swing it into sunlight."}]'::jsonb,
 array['nasa','esa'],
 array['https://science.nasa.gov/mission/webb/','https://www.esa.int/Science_Exploration/Space_Science/Webb'],
 'nasa', now() - interval '18 hours',
 'en', null, 'world.science', array['world.science','science.space'],
 3, 64,
 '[{"question":"What does the L2 position make possible?","options":["A shorter trip home","Passive cooling in constant shadow","A better view of the Sun"],"correct_index":1,"explanation":"Constant shadow allows passive cooling."}]'::jsonb,
 '{"demo": true}'::jsonb, 'demo-en-jwst')

on conflict (content_hash) do nothing;
